### ISSUE TITLE
Hacktoberfest: Audio genre classifcation demo update

### ISSUE THREAD

**Issue by iamleonie** [weaviate-tutorials/DEMO-classification-audio-genre#1]
This is the tracker for polishing the “Audio genre classification” demo. Please refer to our [Hacktoberfest 2023 blog](https://weaviate.io/blog/hacktoberfest-2023) if you want to contribute! 

List of items to contribute:

- [ ]  Run the existing demo and identify and document what exists and what is or isn’t working for the next task
- [ ]  Fixes for any of the identified issues 
    - [ ] <-- List any identified issues here (e.g., data ingestion, dataset issue, search, back-end/API, front-end) -->
- [ ]  Update README to include:
    - [x] Short description
        - [ ] short explanation of how classification with Weaviate works
    - [x] used technology
        - [ ] used Weaviate modules/ML models
    - [x]  demo video
    - [ ] Prerequisites
    - [x] Setup instructions
    - [ ] Usage instructions
    - [ ] Dataset license if applicable
- [ ] Possible improvements/enhancements
    - [ ] Add support for .mp3 extensions in addition to .wav with https://github.com/librosa/librosa#audioread-and-mp3-support (claimed by @MoBanerjee )
    - [ ] Add progress bar to import file
    - [ ] Prettify frontend
    - [ ] Replace current sample data with a larger dataset (e.g., from Kaggle) 
    - [ ] Adding tests (e.g., Pytest, Jest, etc. See our [example](https://github.com/databyjp/distyll) for a starting point)
    - [ ] Conversion to new [Weaviate Python client](https://weaviate.io/blog/collections-python-client-preview)
        - [ ] After Weaviate release 1.22: swap out preview image

**We're open to further suggestions. If you have any further potential improvement ideas, let us know in the comments!**

📣You can contribute parts of the issue or the whole issue. Please comment below to volunteer for the part(s) you want to contribute to.

❓For any questions you might have along the way, join our [Discourse community forum](https://forum.weaviate.io/t/welcome-to-hacktoberfest-2023/764), where we're ready to answer your questions. Or join our dedicated #hacktoberfest channel in our [Weaviate Community Slack](https://weaviate.slack.com/) channel to stay connected and receive real-time support.

✅For your PR, please mention this issue and set @iamleonie as the reviewer and we will review your PR shortly.

**Comment by mohrsalt** [comment]
Hello! Can I try working on this issue- Add support for .mp3 extensions in addition to .wav with https://github.com/librosa/librosa#audioread-and-mp3-support?

**Comment by iamleonie** [comment]
Awesome @MoBanerjee! I have tagged you in the task.

**Comment by iamleonie** [comment]
Thank you, everyone, for contributing to a successful Hacktoberfest 2023!

This issue will now be closed.

If you are still working on any topics, you can, of course, continue on them. However, please note that any PRs created after Oct 31st will not count towards Hacktoberfest.
